### ISSUE TITLE
Error Setting UMB Link!

### ISSUE THREAD

**Issue by Zyntax3rror** [vakobo/Unload#1]
DI1000DD unloads fine...but

I got XMS not found message on USBASPI (v2.27)

Do I have to use JEMMEX for your program to work?

**Comment by vakobo** [comment]
Yes. JEMMEX or HIMEM is required

**Comment by Zyntax3rror** [comment]
Is it possible to add code to unload the USBASPI driver if JEMMEX/HIMEM is not  used?

**Comment by vakobo** [comment]
I will look for this

**Comment by Zyntax3rror** [comment]
ok, that would be great, thanks!

**Comment by vakobo** [comment]
It did something wrong and lead DOS (FreeDOS) to crash. No success yet.

**Comment by vakobo** [comment]
Have some progress

**Comment by Zyntax3rror** [comment]
ok. I imagine it would be a little tricky to get it working

**Comment by vakobo** [comment]
new version ready (branch 2020-08)

**Comment by Zyntax3rror** [comment]
I have tested using 2.27 and 2.27X and It is working perfectly everytime!
Awesome work!
Thanks!
